### ISSUE TITLE
Manifest spec v4

### ISSUE THREAD

**Issue by NebelNidas** [ReviversMC/modget-manifests#8]
Edit: For detailed information on how to use these new and changed tags, see the new [manifest spec](https://github.com/ReviversMC/modget-manifests/blob/v4/doc/spec/manifest-spec.md)!

## Structure
- Give each mod version its own `.yaml` file. This allows us to store an indefinite amount of mod versions without destroying the users' RAM and Internet bandwith. The new structure would look like this:

`main.yaml`:
```yaml
...
versions:
  - 0.3.2
  - 0.3.1
  - 0.3.0
```
And then for each version a different file, e.g. `0.3.2.yaml`:
```yaml
- loader:
    - fabric
  thirdPartyIds:
    modrinth: AANobbMI
    curseforge: 394468
  depends:
    - package: FabricMC.fabric
      version: "*"
  minecraftVersions:
    - 1.17.1
    - 1.17.0
  md5: ...
- loader:
    - forge
  minecraftVersions:
    - 1.17.1
  md5: ...
```
The folder structure would look like this:
```
publisher/
├──modid/
│   ├── main.yaml
│   ├── 0.x/
│   │   ├── 0.3.x/
│   │   │   ├── 0.3.2.yaml
│   │   │   ├── 0.3.1.yaml
│   │   │   ├── 0.3.0.1.yaml
│   │   │   └── 0.3.0.yaml
│   ├── 1.x/
│   │   ├── 1.0.x/
│   │   │   ├── 1.0.0.yaml
│   │   │   ├── 1.0.1.yaml
│   │   │   └── 1.0.2.yaml
│   │   ├── 1.1.x/
│   │   │   ├── 1.1.0.yaml
│   │   │   ├── 1.1.1.yaml
│   │   │   └── 1.1.2.yaml
```

## New
- `iconUrls`: Top-level, links to the Modrinth/CurseForge/GitHub icons of the mod
- `status`: Top-level, can be `active`, `eol`, `unknown` or `abandoned`
- `updatedAlternatives`: Top-level, is used if there is no working version of the mod for newer Minecraft versions and other people have ported it / mods of very similar scope exist
- `authors`: Top-level, format:
  ```yaml
  authors:
    - name: JellySquid
    - name: 2No2Name
  ```
- `bundles`: For each each version, so that if one mod already bundles another mod it depends on, we don't unnecessarily have to download it too. Structure-wise it will be identical to `depends`, `recommends` and `breaks`
- `conflicts`: For each each version, contains packages which cause weird behavior, some kinds of bugs etc. Format see `bundles`.
- `channel`: For each version, can be `alpha`, `beta` or `release`

## Rename / change type
- `chat` → `chats`:
  ```yaml
  chats:
    discord: https://jellysquid.me/discord
    irc: irc://irc.esper.net:6667/fabric
    other:
      - name: Gitter
        url: https://gitter.im/Open-Shell
  ```
- `loader` → `loaders`
- `modType` → `fileType`
- `side` → `environment`:
  ```yaml
  environment:
    client: optional
    server: required
  ```
  Possible values: `unsupported`, `optional` and `required`
- `downloadPageUrls` and `fileUrls`:
  ```yaml
  fileUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/sodium/download/3488836/file
    sourceControl: https://github.com/CaffeineMC/sodium-fabric/releases/download/mc1.17.1-0.3.2/sodium-fabric-mc1.17.1-0.3.2+build.7.jar
    other:
      - name: Example site
        url: https://example.com/
  ```

## Move from top-level to versions
- `loaders`
- `thirdPartyIds`
- `fileType`
- `license`

## Miscellaneous:
- Strip some Minecraft versions of their tailing `.0` (e.g. `1.17.0` →`1.17`) to comply with Minecraft's official version names

## Lookup Table
- Add `loaders` to each package
- Move `tags` above `packages`
- Rename `names` to `alternativeNames`
